version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/django_dev.dockerfile
    volumes:
      - .:/app/dev/etpph
    env_file: ./docker/.env 
    ports:
      - 80:80
    image: etpph:dev
    container_name: etpph_dev
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    command: python manage.py runserver 0.0.0.0:80
    links:
      - db
    depends_on:
      - db

  db:
    image: 'postgres:14.4-alpine3.16'
    env_file: ./docker/.env
    hostname: db_postgress
    container_name: db_postgress
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    # ports:
    #   - '5432:5432'
    volumes:
      - './database/data:/var/lib/postgresql/data'

  redis:
    hostname: redis_dev
    image: redis:7.0.4-alpine3.16
    command: redis-server --requirepass etpphredis
    container_name: redis_dev
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  192.168.5.0/24